# General Unix-like commands
alias ll="ls -lh"
alias la="ls -lha"
alias lt="ls -lhta"
alias repos="cd /d/Repos"
alias bash-config="cd /d/Repos/bash-config"
alias ..="cd .."
alias ...="cd ../.."

# Git commands
alias gfa="git fetch -A"
alias gaa="git add -A"
alias gc="git commit -m"
alias gcc="git checkout"
alias gcd="git checkout dev"
alias gcm="git checkout main"
alias gccb="git checkout -b"
alias push="git push"
alias pull="git pull"
alias continue="git rebase --continue"